### ISSUE TITLE
Adding new product with empty string

### ISSUE THREAD

**Issue by VladimirAnaniev** [naskogeorgiev92/simple-shopping-list#1]
App crashes, check for input is needed

**Comment by Juhojou** [comment]
Hi,

I was wondering is this your school project or something? I am student of CSE and I am searching open-source projects for my school exercise where I need to fix a bug for open-source project. So is it possible if I fix this problem?

Br,
Juho

**Comment by naskogeorgiev92** [comment]
Hello,

Yes this is a school project. It would be nice if you are able to fix that. I tried to do it, but the Alert Dialog closes before the validation error is displayed.

Regards,
Nasko

**Comment by Juhojou** [comment]
Hi,

Ok I will start to fix this!

Br,
Juho
